### PR TITLE
some updates after an evening of use

### PR DESCRIPTION
**Pull request by ZeroChaos-**
clean the wifi scan result data to free ram
I have been noticing that the existing code has been crashing
frequently.  The example code frees ram, might not fix the crash, but
probably won't hurt.  jhewitt doesn't do it, so maybe it's like the
close door button on the elevator.

Added some startup output for errors and successes

Reduced calls to displayDevices for predictability.  Now displayDevices
is called once per wifi scan instead of once per found device.  This
drastically reduces flashing on the screen.

Rewrote displayDevices to not turn the page when there is nothing to
write.

Rewrote displayDevices to show the header on every page.

Switched UPDATE_MODE_ per the docs to reduce flashing and improve speed
while not affecting text quality.

### CODE REVIEW

**Comment by ZeroChaos-** [comment]
Hi!  I bought this m5paper a few weeks ago hoping to work on something exactly like this, so when I saw your work I got pretty excited.  I'm willing to back out any of this which you don't like but after an evening of testing before and after I feel these changes really improve the usability.  I strongly encourage you to test this version if you have any questions about the UPDATE_MODE changes, also if you want to see the change in user experience by dropping so many calls to displayDevices.

**Comment by ZeroChaos-** [comment]
Just to save searching, UPDATE_MODE code: https://github.com/m5stack/M5EPD/blob/main/src/M5EPD_Driver.h

**Comment by ZeroChaos-** [comment]
I can confirm after a fun morning of use that this works well, looks good, and does NOT fix the random crash I see every time I hit about 150 total devices.  I'll investigate that on a follow up PR, but this crash is preexisting and unaffected by this PR so not a reason to prevent merge.

**Comment by lukeswitz** [comment]
> I can confirm after a fun morning of use that this works well, looks good, and does NOT fix the random crash I see every time I hit about 150 total devices. I'll investigate that on a follow up PR, but this crash is preexisting and unaffected by this PR so not a reason to prevent merge.

The crash- That’s a WDT issue. 

And you can remove lowest rssi items from the list or just overwrite the array index. It’s statically set to 150 as it stands.

**Comment by ZeroChaos-** [comment]
Heh, it crashes at 150 because it's set to https://github.com/colonelpanichacks/m5paper-Wardriver/blob/main/m5paperwardriver/m5paperwardriver.ino#L45

I'm going to change that value and monitor memory usage to see if I can find a much larger number which is still safe.  I plan this to be a follow up PR, but I can add it here if I get it done before you have time to review this work.

**Comment by lukeswitz** [comment]
This is a hobby project. Don’t rush. Enjoy and commit when things work. Cheers and happy tinkering.

**Comment by ZeroChaos-** [comment]
Thanks, I appreciate it.  I'd like to try to keep the individual PRs smaller so they are easy to review.  No need to rush to review and merge this, but it's better if this work gets merged in one PR and what I'm already working on gets merged in another :-)  Especially because what I'm working on next requires a lot more testing but the changes here stand alone and are working well.

**Comment by lukeswitz** [comment]
> Thanks, I appreciate it. I'd like to try to keep the individual PRs smaller so they are easy to review. No need to rush to review and merge this, but it's better if this work gets merged in one PR and what I'm already working on gets merged in another :-) Especially because what I'm working on next requires a lot more testing but the changes here stand alone and are working well.

Keep your commits small & PR as needed. Not sure why you’re pushing this repo to follow your dev schedule.

Happy coding.

**Comment by ZeroChaos-** [comment]
> > Thanks, I appreciate it. I'd like to try to keep the individual PRs smaller so they are easy to review. No need to rush to review and merge this, but it's better if this work gets merged in one PR and what I'm already working on gets merged in another :-) Especially because what I'm working on next requires a lot more testing but the changes here stand alone and are working well.
> 
> Keep your commits small & PR as needed.

That's the plan.  I have some ideas for improvements and am trying to separate the commits and the PRs logically so to not make review more difficult.

>Not sure why you’re pushing this repo to follow your dev schedule.

That was not my intent, I even specifically said "no need to rush to review and merge this".  I understand that this is someone else's little passion project, and it's been less than a day that I have been playing with it.  I did not mean to rush anyone or suggest I was the project manager.  I was only trying to make clear that smaller PRs are usually easier to handle and as such I was planning to separate my work on the 150 device limit into a new PR, so this PR is ready for review and merge.

**Comment by lukeswitz** [comment]
Sounds good. Do you have the serial logs of the crash? I can probably help with that.

**Comment by ZeroChaos-** [comment]
> Sounds good. Do you have the serial logs of the crash? I can probably help with that.

To avoid confusing this PR with unrelated issues and testing I've logged my thoughts on this topic in a new issue https://github.com/colonelpanichacks/m5paper-Wardriver/issues/6

**Comment by ZeroChaos-** [comment]
Okay, I'm officially a little sorry that I might have gotten carried away.  I've added a bunch of stuff.  I'm happy to discuss any/all of it if you don't like the choices I've made.  I'm a little too excited and rather enjoying working on this, but my goal isn't to take over your project.  Short version of recent changes from the commit log

- Able to track 825 devices (logs everything)
- Automatically overwrites devices not see in the longest time.
- Add battery reading and adjust the line between header and devices based on battery percentage.
- Only show devices seen in the last 120 seconds (but track 825 and log everything).
- Update startup screen with more info.
- Add more serial prints with startup screen info in case screen is not functional.

**Comment by ZeroChaos-** [comment]
Added a mutex to protect deviceList and it seems to have fixed the random crashes/reboots I was experiencing.

**Comment by ZeroChaos-** [comment]
I've been running for 925 minutes, tracking 1025 unique devices.  No crashes, still discovering new devices, automatically overwriting old, sorting by rssi, and displaying correctly.  Stability resolved.

**Comment by ZeroChaos-** [comment]
After a discussion with jhewitt I migrated the wifi scanning to async and set the time per channel to 103ms
https://github.com/JosephHewitt/wardriver_rev3/issues/177

This way we scan basically all the time so there isn't a major benefit to staying on a channel longer than 1 beacon interval.

**Comment by lukeswitz** [comment]
Typically we don’t use async with the esp32s for stability, curious why you went that route? And thanks for talking with Hewitt he knows his stuff. 

I ran your code at various speed and found a few things worth noting:


#### Asynchronous WiFi Scanning `(WiFi.scanNetworks(true))`:

- Crashes/resets due to rapid successive scans without sufficient delay​: 
   - [ESP32 Forum](https://esp32.com/viewtopic.php?t=25584)
   - [GitHub](https://github.com/espressif/arduino-esp32/issues/354)

- Overwriting scan results from previous runs (timing isn't handled correctly​)
   - [GitHub](https://github.com/espressif/arduino-esp32/issues/354)

- Incomplete scans from `WiFi.scanComplete()` not properly checked for WIFI_SCAN_RUNNING​
   - [GitHub](https://github.com/espressif/arduino-esp32/issues/354)

- Infinite loops- unmanaged scan status, causing the scan to never finish​
   - [ESP32 Forum](https://esp32.com/viewtopic.php?t=25584)
   - [GitHub](https://github.com/espressif/arduino-esp32/issues/354)


#### Mutex Locking During Delays:

- Deadlocks by locking mutex during delay() calls, blocking other tasks
   - [GitHub](https://github.com/espressif/arduino-esp32/issues/354)

- Performance bottlenecks from preventing access to shared resources during the delay​
   - [GitHub](https://github.com/espressif/arduino-esp32/issues/354)

- Reduced system responsiveness due to extended mutex locking, stalling other processes​
   - [GitHub](https://github.com/espressif/arduino-esp32/issues/354)

#### Potential Fix Ideas
- Add a delay after each WiFi scan in `startWiFiScan()` to prevent crashes and overwriting results.
- Check if the scan is still running in `WiFi.scanComplete()` to ensure all results are processed.
- Unlock the mutex before calling delay() in `displayDevices()` to avoid deadlocks and improve performance.
- Ensure the mutex isn’t held for too long in displayDevices() to prevent slowing down the system.

**Comment by ZeroChaos-** [comment]
> Typically we don’t use async with the esp32s for stability, curious why you went that route? And thanks for talking with Hewitt he knows his stuff.
> 
Because previously we aren't scanning during display and that's a looooooong time for war driving code to be doing nothing.  I was not aware of the known stability issues.

> #### Potential Fix Ideas
> * Add a delay after each WiFi scan in `startWiFiScan()` to prevent crashes and overwriting results.
I had that but pulled it in a mindless pursuit of speed.  I will add it back.

> * Check if the scan is still running in `WiFi.scanComplete()` to ensure all results are processed.
That seems reasonable, I will try.

> * Unlock the mutex before calling delay() in `displayDevices()` to avoid deadlocks and improve performance.
I do, unless you see somewhere I don't?
> * Ensure the mutex isn’t held for too long in displayDevices() to prevent slowing down the system.
I tried a lot of places to lock and unlock and these are the smallest locks without either deadlock or more significant refactoring that I could manage.  Totally open to improvements but the locks are reasonably small right now.

**Comment by lukeswitz** [comment]
Oh; your code is perfect I forgot. Quite defensive for someone who can’t admit they’re wrong on anything. But that’s a you problem. May you live in interesting times.

**Comment by lukeswitz** [comment]
Oh got it, you don’t get non-blocking code. Can’t help ya as you’re pretty dead set about your code being gods gift. Enjoy.

**Comment by ZeroChaos-** [comment]
I see the inline responses to your fixes got rendered badly, and that is my fault.  Perhaps you missed where I said I would implement your suggestions?

I admit I am dead set at trying to scan asynchronous for the reason of not missing networks, but there are other ways to handle it (such as pinning the scan to the other cpu) if this way is a problem.  This is just the first way I tested, and as you see the commit was last night so it hasn't been tested much.

**Comment by lukeswitz** [comment]
Async just causes the esp32 wardrivers to crash. There’s not one way to learn, and I admit I don’t know a lot about this stuff. But, I have written, tweaked and tested nethugger code for years now. It could be better but sometimes being able to use something trumps minimal optimizations. 

That said it’s cool what you’re doing in taking it seriously. I come off as a jaded cynic because I guess that’s just what 20 years in this space did to me. 

You don’t have to implement anything I was simply pointing out that a scan needs to complete, doesn’t matter how it happens. And with async I’d get back and the units that work fine stationary couldn’t handle the packets properly in motion without performing a check that really wasn’t needed in a properly written loop. 

Is the epaper dual-core? Could be useful to pin display/i2c to one and scans to another. Goal for me is adding options like AtomGPS or nano in conjunction. But a $25 android running wigle will beat anything a plain esp32 module can do. 

/rant

**Comment by ZeroChaos-** [comment]
I am traveling and can't code or test, but I have been running my code for >16 hours without a noticable crash.  I am not tracking well enough to say it hasn't crashed, but it seems to be at least reliable enough that I don't notice.  I still agree with many of your suggestions as I said above, and I will check those other links to learn about the other cases where it was unreliable.

M5paper is dual core afaik. Arduino lets me set core 0 and core 1 anyway :-). I have minimal esp32 experience, so who knows.  I want to pin the tasks to separate cores but when I read that code in jhewitt's repo it was above my head so I went with async for now.

I am happy to have the code review, I am not a professional programmer and my esp32 experience is maybe a total of 800 lines of code.  That said, I would appreciate if you kept the attacks to my code.

**Comment by lukeswitz** [comment]
Apologies if I was rude. You’re doing good work here and it should not be subject to my criticism or interpretation. Best,

Luke

**Pull request merged**
